# Generated by Django 3.1 on 2020-08-28 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_avtive',
            new_name='is_active',
        ),
    ]
